apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-server
  labels:
    app: ws-server
spec:
  selector:
    matchLabels:
      app: ws-server
  template:
    metadata:
      labels:
        app: ws-server
    spec:
      containers:
      - name: ws-server
        image: "satyamz/ws-server:v1"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ws-service
spec:
  selector:
    app: ws-server
  type: NodePort
  ports:
     - name: app
       port: 8080
       protocol: TCP
       nodePort: 32212